services:
  api:
    container_name: evolution_audio_converter
    image: atendai/evolution-audio-converter:latest
    restart: always
    ports:
      - ${PORT-:4040}:4040
    networks:
      - evolution-net
    environment:
      - PORT=4040
      - API_KEY=${EVO_API_KEY}
    expose:
      - 4040


networks:
  evolution-net:
    name: evolution-net
    driver: bridge
